version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:ACCOUNT_ID:task-definition/brain-tasks-app:1"
        LoadBalancerInfo:
          ContainerName: "brain-tasks-app"
          ContainerPort: 80
        PlatformVersion: "LATEST"
        NetworkConfiguration:
          AwsvpcConfiguration:
            Subnets:
              - "subnet-xxxxx"
            SecurityGroups:
              - "sg-xxxxx"
            AssignPublicIp: "ENABLED"

Hooks:
  - BeforeInstall: "PreInstallScript"
  - AfterInstall: "PostInstallScript"
  - BeforeAllowTraffic: "BeforeTrafficScript"
  - AfterAllowTraffic: "AfterTrafficScript"
